#
# This is a basic build configuration for Travis CI.
# See http://conda.pydata.org/docs/travis.html for more info.
#

version: '{build}'

image:
  - Ubuntu

configuration: Release

platform:
  - x64

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH";
  - export SKIP_PSQL_TESTS=1;
  - hash -r
  - conda install -y -c conda-forge mamba;
  - conda info -a
  - mamba env create
  - source activate xcube_geodb
  - mamba install -y -c conda-forge postgis;
  - cd xcube_geodb/sql;
  - make install;
  - cd ../..;
  - python setup.py install
  - cp tests/envs/.env_ci tests/envs/.env

build_script:
  - for f in xcube_geodb/sql/*.sql;
        do
          pgsanity $f;
        done
  - py.test -v --cov=xcube_geodb
  - pip install codecov
  - codecov --env TRAVIS_PYTHON_VERSION
